services:
  postgres:
  # going to use the ankane image since it has pgvector pre-installed
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-user}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password1230}
      - POSTGRES_DB=${DATABASE_NAME:-vectordb}
    volumes:
      - pg_data:/var/lib/postgresql/data
    # TODO: healthcheck
  
  redis:
    # TODO: change to redis-stack. Comes with a lot of useful features
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pg_data: